name: CI

on:
  push:
    branches-ignore:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    name: Run CI checks
    uses: ./.github/workflows/backend-ci.yml
    permissions:
      contents: read
